"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DateRangeErrorEnum(google.protobuf.message.Message):
    """Proto file describing date range errors.

    Container for enum describing possible date range errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _DateRangeError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _DateRangeErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DateRangeError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        INVALID_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 2
        """Invalid date."""

        START_DATE_AFTER_END_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 3
        """The start date was after the end date."""

        CANNOT_SET_DATE_TO_PAST: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 4
        """Cannot set date to past time"""

        AFTER_MAXIMUM_ALLOWABLE_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 5
        """A date was used that is past the system "last" date."""

        CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 6
        """Trying to change start date on a resource that has started."""

    class DateRangeError(_DateRangeError, metaclass=_DateRangeErrorEnumTypeWrapper):
        """Enum describing possible date range errors."""
        pass

    UNSPECIFIED: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    INVALID_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 2
    """Invalid date."""

    START_DATE_AFTER_END_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 3
    """The start date was after the end date."""

    CANNOT_SET_DATE_TO_PAST: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 4
    """Cannot set date to past time"""

    AFTER_MAXIMUM_ALLOWABLE_DATE: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 5
    """A date was used that is past the system "last" date."""

    CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED: DateRangeErrorEnum.DateRangeError.ValueType = ...  # 6
    """Trying to change start date on a resource that has started."""


    def __init__(self,
        ) -> None: ...
global___DateRangeErrorEnum = DateRangeErrorEnum
