"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ScanConfigError(google.protobuf.message.Message):
    """Defines a custom error message used by CreateScanConfig and UpdateScanConfig
    APIs when scan configuration validation fails. It is also reported as part of
    a ScanRunErrorTrace message if scan validation fails due to a scan
    configuration error.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Code:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _CodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Code.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        CODE_UNSPECIFIED: ScanConfigError.Code.ValueType = ...  # 0
        """There is no error."""

        OK: ScanConfigError.Code.ValueType = ...  # 0
        """There is no error."""

        INTERNAL_ERROR: ScanConfigError.Code.ValueType = ...  # 1
        """Indicates an internal server error.
        Please DO NOT USE THIS ERROR CODE unless the root cause is truly unknown.
        """

        APPENGINE_API_BACKEND_ERROR: ScanConfigError.Code.ValueType = ...  # 2
        """One of the seed URLs is an App Engine URL but we cannot validate the scan
        settings due to an App Engine API backend error.
        """

        APPENGINE_API_NOT_ACCESSIBLE: ScanConfigError.Code.ValueType = ...  # 3
        """One of the seed URLs is an App Engine URL but we cannot access the
        App Engine API to validate scan settings.
        """

        APPENGINE_DEFAULT_HOST_MISSING: ScanConfigError.Code.ValueType = ...  # 4
        """One of the seed URLs is an App Engine URL but the Default Host of the
        App Engine is not set.
        """

        CANNOT_USE_GOOGLE_COM_ACCOUNT: ScanConfigError.Code.ValueType = ...  # 6
        """Google corporate accounts can not be used for scanning."""

        CANNOT_USE_OWNER_ACCOUNT: ScanConfigError.Code.ValueType = ...  # 7
        """The account of the scan creator can not be used for scanning."""

        COMPUTE_API_BACKEND_ERROR: ScanConfigError.Code.ValueType = ...  # 8
        """This scan targets Compute Engine, but we cannot validate scan settings
        due to a Compute Engine API backend error.
        """

        COMPUTE_API_NOT_ACCESSIBLE: ScanConfigError.Code.ValueType = ...  # 9
        """This scan targets Compute Engine, but we cannot access the Compute Engine
        API to validate the scan settings.
        """

        CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT: ScanConfigError.Code.ValueType = ...  # 10
        """The Custom Login URL does not belong to the current project."""

        CUSTOM_LOGIN_URL_MALFORMED: ScanConfigError.Code.ValueType = ...  # 11
        """The Custom Login URL is malformed (can not be parsed)."""

        CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS: ScanConfigError.Code.ValueType = ...  # 12
        """The Custom Login URL is mapped to a non-routable IP address in DNS."""

        CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS: ScanConfigError.Code.ValueType = ...  # 13
        """The Custom Login URL is mapped to an IP address which is not reserved for
        the current project.
        """

        CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 14
        """The Custom Login URL has a non-routable IP address."""

        CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 15
        """The Custom Login URL has an IP address which is not reserved for the
        current project.
        """

        DUPLICATE_SCAN_NAME: ScanConfigError.Code.ValueType = ...  # 16
        """Another scan with the same name (case-sensitive) already exists."""

        INVALID_FIELD_VALUE: ScanConfigError.Code.ValueType = ...  # 18
        """A field is set to an invalid value."""

        FAILED_TO_AUTHENTICATE_TO_TARGET: ScanConfigError.Code.ValueType = ...  # 19
        """There was an error trying to authenticate to the scan target."""

        FINDING_TYPE_UNSPECIFIED: ScanConfigError.Code.ValueType = ...  # 20
        """Finding type value is not specified in the list findings request."""

        FORBIDDEN_TO_SCAN_COMPUTE: ScanConfigError.Code.ValueType = ...  # 21
        """Scan targets Compute Engine, yet current project was not whitelisted for
        Google Compute Engine Scanning Alpha access.
        """

        FORBIDDEN_UPDATE_TO_MANAGED_SCAN: ScanConfigError.Code.ValueType = ...  # 43
        """User tries to update managed scan"""

        MALFORMED_FILTER: ScanConfigError.Code.ValueType = ...  # 22
        """The supplied filter is malformed. For example, it can not be parsed, does
        not have a filter type in expression, or the same filter type appears
        more than once.
        """

        MALFORMED_RESOURCE_NAME: ScanConfigError.Code.ValueType = ...  # 23
        """The supplied resource name is malformed (can not be parsed)."""

        PROJECT_INACTIVE: ScanConfigError.Code.ValueType = ...  # 24
        """The current project is not in an active state."""

        REQUIRED_FIELD: ScanConfigError.Code.ValueType = ...  # 25
        """A required field is not set."""

        RESOURCE_NAME_INCONSISTENT: ScanConfigError.Code.ValueType = ...  # 26
        """Project id, scanconfig id, scanrun id, or finding id are not consistent
        with each other in resource name.
        """

        SCAN_ALREADY_RUNNING: ScanConfigError.Code.ValueType = ...  # 27
        """The scan being requested to start is already running."""

        SCAN_NOT_RUNNING: ScanConfigError.Code.ValueType = ...  # 28
        """The scan that was requested to be stopped is not running."""

        SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT: ScanConfigError.Code.ValueType = ...  # 29
        """One of the seed URLs does not belong to the current project."""

        SEED_URL_MALFORMED: ScanConfigError.Code.ValueType = ...  # 30
        """One of the seed URLs is malformed (can not be parsed)."""

        SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS: ScanConfigError.Code.ValueType = ...  # 31
        """One of the seed URLs is mapped to a non-routable IP address in DNS."""

        SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS: ScanConfigError.Code.ValueType = ...  # 32
        """One of the seed URLs is mapped to an IP address which is not reserved
        for the current project.
        """

        SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 33
        """One of the seed URLs has on-routable IP address."""

        SEED_URL_HAS_UNRESERVED_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 35
        """One of the seed URLs has an IP address that is not reserved
        for the current project.
        """

        SERVICE_ACCOUNT_NOT_CONFIGURED: ScanConfigError.Code.ValueType = ...  # 36
        """The Web Security Scanner service account is not configured under the
        project.
        """

        TOO_MANY_SCANS: ScanConfigError.Code.ValueType = ...  # 37
        """A project has reached the maximum number of scans."""

        UNABLE_TO_RESOLVE_PROJECT_INFO: ScanConfigError.Code.ValueType = ...  # 38
        """Resolving the details of the current project fails."""

        UNSUPPORTED_BLACKLIST_PATTERN_FORMAT: ScanConfigError.Code.ValueType = ...  # 39
        """One or more blacklist patterns were in the wrong format."""

        UNSUPPORTED_FILTER: ScanConfigError.Code.ValueType = ...  # 40
        """The supplied filter is not supported."""

        UNSUPPORTED_FINDING_TYPE: ScanConfigError.Code.ValueType = ...  # 41
        """The supplied finding type is not supported. For example, we do not
        provide findings of the given finding type.
        """

        UNSUPPORTED_URL_SCHEME: ScanConfigError.Code.ValueType = ...  # 42
        """The URL scheme of one or more of the supplied URLs is not supported."""

    class Code(_Code, metaclass=_CodeEnumTypeWrapper):
        """Output only.
        Defines an error reason code.
        Next id: 44
        """
        pass

    CODE_UNSPECIFIED: ScanConfigError.Code.ValueType = ...  # 0
    """There is no error."""

    OK: ScanConfigError.Code.ValueType = ...  # 0
    """There is no error."""

    INTERNAL_ERROR: ScanConfigError.Code.ValueType = ...  # 1
    """Indicates an internal server error.
    Please DO NOT USE THIS ERROR CODE unless the root cause is truly unknown.
    """

    APPENGINE_API_BACKEND_ERROR: ScanConfigError.Code.ValueType = ...  # 2
    """One of the seed URLs is an App Engine URL but we cannot validate the scan
    settings due to an App Engine API backend error.
    """

    APPENGINE_API_NOT_ACCESSIBLE: ScanConfigError.Code.ValueType = ...  # 3
    """One of the seed URLs is an App Engine URL but we cannot access the
    App Engine API to validate scan settings.
    """

    APPENGINE_DEFAULT_HOST_MISSING: ScanConfigError.Code.ValueType = ...  # 4
    """One of the seed URLs is an App Engine URL but the Default Host of the
    App Engine is not set.
    """

    CANNOT_USE_GOOGLE_COM_ACCOUNT: ScanConfigError.Code.ValueType = ...  # 6
    """Google corporate accounts can not be used for scanning."""

    CANNOT_USE_OWNER_ACCOUNT: ScanConfigError.Code.ValueType = ...  # 7
    """The account of the scan creator can not be used for scanning."""

    COMPUTE_API_BACKEND_ERROR: ScanConfigError.Code.ValueType = ...  # 8
    """This scan targets Compute Engine, but we cannot validate scan settings
    due to a Compute Engine API backend error.
    """

    COMPUTE_API_NOT_ACCESSIBLE: ScanConfigError.Code.ValueType = ...  # 9
    """This scan targets Compute Engine, but we cannot access the Compute Engine
    API to validate the scan settings.
    """

    CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT: ScanConfigError.Code.ValueType = ...  # 10
    """The Custom Login URL does not belong to the current project."""

    CUSTOM_LOGIN_URL_MALFORMED: ScanConfigError.Code.ValueType = ...  # 11
    """The Custom Login URL is malformed (can not be parsed)."""

    CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS: ScanConfigError.Code.ValueType = ...  # 12
    """The Custom Login URL is mapped to a non-routable IP address in DNS."""

    CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS: ScanConfigError.Code.ValueType = ...  # 13
    """The Custom Login URL is mapped to an IP address which is not reserved for
    the current project.
    """

    CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 14
    """The Custom Login URL has a non-routable IP address."""

    CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 15
    """The Custom Login URL has an IP address which is not reserved for the
    current project.
    """

    DUPLICATE_SCAN_NAME: ScanConfigError.Code.ValueType = ...  # 16
    """Another scan with the same name (case-sensitive) already exists."""

    INVALID_FIELD_VALUE: ScanConfigError.Code.ValueType = ...  # 18
    """A field is set to an invalid value."""

    FAILED_TO_AUTHENTICATE_TO_TARGET: ScanConfigError.Code.ValueType = ...  # 19
    """There was an error trying to authenticate to the scan target."""

    FINDING_TYPE_UNSPECIFIED: ScanConfigError.Code.ValueType = ...  # 20
    """Finding type value is not specified in the list findings request."""

    FORBIDDEN_TO_SCAN_COMPUTE: ScanConfigError.Code.ValueType = ...  # 21
    """Scan targets Compute Engine, yet current project was not whitelisted for
    Google Compute Engine Scanning Alpha access.
    """

    FORBIDDEN_UPDATE_TO_MANAGED_SCAN: ScanConfigError.Code.ValueType = ...  # 43
    """User tries to update managed scan"""

    MALFORMED_FILTER: ScanConfigError.Code.ValueType = ...  # 22
    """The supplied filter is malformed. For example, it can not be parsed, does
    not have a filter type in expression, or the same filter type appears
    more than once.
    """

    MALFORMED_RESOURCE_NAME: ScanConfigError.Code.ValueType = ...  # 23
    """The supplied resource name is malformed (can not be parsed)."""

    PROJECT_INACTIVE: ScanConfigError.Code.ValueType = ...  # 24
    """The current project is not in an active state."""

    REQUIRED_FIELD: ScanConfigError.Code.ValueType = ...  # 25
    """A required field is not set."""

    RESOURCE_NAME_INCONSISTENT: ScanConfigError.Code.ValueType = ...  # 26
    """Project id, scanconfig id, scanrun id, or finding id are not consistent
    with each other in resource name.
    """

    SCAN_ALREADY_RUNNING: ScanConfigError.Code.ValueType = ...  # 27
    """The scan being requested to start is already running."""

    SCAN_NOT_RUNNING: ScanConfigError.Code.ValueType = ...  # 28
    """The scan that was requested to be stopped is not running."""

    SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT: ScanConfigError.Code.ValueType = ...  # 29
    """One of the seed URLs does not belong to the current project."""

    SEED_URL_MALFORMED: ScanConfigError.Code.ValueType = ...  # 30
    """One of the seed URLs is malformed (can not be parsed)."""

    SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS: ScanConfigError.Code.ValueType = ...  # 31
    """One of the seed URLs is mapped to a non-routable IP address in DNS."""

    SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS: ScanConfigError.Code.ValueType = ...  # 32
    """One of the seed URLs is mapped to an IP address which is not reserved
    for the current project.
    """

    SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 33
    """One of the seed URLs has on-routable IP address."""

    SEED_URL_HAS_UNRESERVED_IP_ADDRESS: ScanConfigError.Code.ValueType = ...  # 35
    """One of the seed URLs has an IP address that is not reserved
    for the current project.
    """

    SERVICE_ACCOUNT_NOT_CONFIGURED: ScanConfigError.Code.ValueType = ...  # 36
    """The Web Security Scanner service account is not configured under the
    project.
    """

    TOO_MANY_SCANS: ScanConfigError.Code.ValueType = ...  # 37
    """A project has reached the maximum number of scans."""

    UNABLE_TO_RESOLVE_PROJECT_INFO: ScanConfigError.Code.ValueType = ...  # 38
    """Resolving the details of the current project fails."""

    UNSUPPORTED_BLACKLIST_PATTERN_FORMAT: ScanConfigError.Code.ValueType = ...  # 39
    """One or more blacklist patterns were in the wrong format."""

    UNSUPPORTED_FILTER: ScanConfigError.Code.ValueType = ...  # 40
    """The supplied filter is not supported."""

    UNSUPPORTED_FINDING_TYPE: ScanConfigError.Code.ValueType = ...  # 41
    """The supplied finding type is not supported. For example, we do not
    provide findings of the given finding type.
    """

    UNSUPPORTED_URL_SCHEME: ScanConfigError.Code.ValueType = ...  # 42
    """The URL scheme of one or more of the supplied URLs is not supported."""


    CODE_FIELD_NUMBER: builtins.int
    FIELD_NAME_FIELD_NUMBER: builtins.int
    code: global___ScanConfigError.Code.ValueType = ...
    """Output only. Indicates the reason code for a configuration failure."""

    field_name: typing.Text = ...
    """Output only. Indicates the full name of the ScanConfig field that triggers this error,
    for example "scan_config.max_qps". This field is provided for
    troubleshooting purposes only and its actual value can change in the
    future.
    """

    def __init__(self,
        *,
        code : global___ScanConfigError.Code.ValueType = ...,
        field_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","field_name",b"field_name"]) -> None: ...
global___ScanConfigError = ScanConfigError
